# Generated by Django 3.0.3 on 2020-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_first_name', models.CharField(max_length=255)),
                ('emp_last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=1000)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Select', max_length=100)),
                ('fb_link', models.CharField(max_length=1000)),
                ('twitter_link', models.CharField(max_length=1000)),
                ('linkedin_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
