# Generated by Django 3.0.3 on 2020-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_first_name',
            new_name='emp_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='linkedin_link',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_no',
            field=models.CharField(default='+911234567890', max_length=13),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
